name: Scala CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # also get the tags so git based sbt versioning works
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: sbt test
  check-quality-gates:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Run code coverage
        run: sbt clean coverage test coverageReport
      - name: Upload to codecov
        run: bash <(curl -s https://codecov.io/bash)
  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: verify-precondition-create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish locally
        run: sbt publishLocal
        # '0.+' will keep on working until 1.x is released
      - run: curl -fLo cs https://git.io/coursier-cli-linux &&
          chmod +x cs &&
          ./cs bootstrap io.github.lhohan::tech-radar-from-csv:0.+ --standalone -o techradar -f
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./techradar
          token: ${{ secrets.GITHUB_TOKEN }}
  verify-precondition-create-release:
#   If version is v1+ (more accurately not v0+, quick fix) we fail
    if: startsWith(github.ref, 'refs/tags/v1')
    needs: [build, check-quality-gates]
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
