name: Scala CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: sbt test
      # Prepare for release job: transfer artifact
      - name: Publish locally
        if: startsWith(github.ref, 'refs/tags/v')
        run: sbt publishLocal
      - run: mkdir -p artifacts
        if: startsWith(github.ref, 'refs/tags/v')
      - uses: actions/upload-artifact@master
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: ivy2
          path: /home/runner/.ivy2/**
  format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check formatting
        run: sbt scalafmtCheckAll
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Coursier
        run: curl -fLo cs https://git.io/coursier-cli-linux &&
          chmod +x cs
      - run: mkdir -p /home/runner/.ivy2
      - uses: actions/download-artifact@v2
        with:
          name: ivy2
          path: /home/runner/.ivy2/
      - run: cs bootstrap io.github.lhohan::tech-radar-from-csv:0.+ --standalone -o techradar -f
      - uses: actions/upload-artifact@master
        with:
         name: techradar
         path: ./techradar
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: ivy2

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run code coverage
        run: sbt clean coverage test coverageReport
      - name: Upload to codecov
        run: bash <(curl -s https://codecov.io/bash)