name: Scala CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # also get the tags so git based sbt versioning works
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run build commands
        run: build/build.sh
      - name: Upload to codecov
        run: bash <(curl -s https://codecov.io/bash)
  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      #   If version is v1+ (more accurately not v0+, quick fix) we fail, Coursier step below needs updating
      - run: exit 1
        if: startsWith(github.ref, 'refs/tags/v1')
      - uses: actions/checkout@v2
      - name: Create release executable
        run: build/create-executable.sh
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./techradar
          token: ${{ secrets.GITHUB_TOKEN }}
